export const ActionTypes = {
	LOGIN_START: "LOGIN_START",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILED: "LOGIN_FAILED",

	AUTO_LOGIN_SUCCESS:"AUTO_LOGIN_SUCCESS",
	LOG_OUT:"LOG_OUT",

	GET_SUBMISSIONS_START:"GET_SUBMISSIONS_START",
	GET_SUBMISSIONS_SUCCESS:"GET_SUBMISSIONS_SUCCESS",
	GET_SUBMISSIONS_FAILED:"GET_SUBMISSIONS_FAILED",

	GET_SUBMISSIONS1_START:"GET_SUBMISSIONS1_START",
	GET_SUBMISSIONS1_SUCCESS:"GET_SUBMISSIONS1_SUCCESS",
	GET_SUBMISSIONS1_FAILED:"GET_SUBMISSIONS1_FAILED",

	GET_ACTIVIDADES_START:"GET_ACTIVIDADES_START",
	GET_ACTIVIDADES_SUCCESS:"GET_ACTIVIDADES_SUCCESS",
	GET_ACTIVIDADES_FAILED:"GET_ACTIVIDADES_FAILED",

	GET_HORARIOS_START:"GET_HORARIOS_START",
	GET_HORARIOS_SUCCESS:"GET_HORARIOS_SUCCESS",
	GET_HORARIOS_FAILED:"GET_HORARIOS_FAILED",

	GET_PROMOCIONES_START:"GET_PROMOCIONES_START",
	GET_PROMOCIONES_SUCCESS:"GET_PROMOCIONES_SUCCESS",
	GET_PROMOCIONES_FAILED:"GET_PROMOCIONES_FAILED",

	GET_PUNTOS_START:"GET_PUNTOS_START",
	GET_PUNTOS_SUCCESS:"GET_PUNTOS_SUCCESS",
	GET_PUNTOS_FAILED:"GET_PUNTOS_FAILED",

	GET_WALLET_START:"GET_WALLET_START",
	GET_WALLET_SUCCESS:"GET_WALLET_SUCCESS",
	GET_WALLET_FAILED:"GET_WALLET_FAILED",

	GET_GRAFICO_START:"GET_GRAFICO_START",
	GET_GRAFICO_SUCCESS:"GET_GRAFICO_SUCCESS",
	GET_GRAFICO_FAILED:"GET_GRAFICO_FAILED",

	GET_DESCUENTO_START:"GET_DESCUENTO_START",
	GET_DESCUENTO_SUCCESS:"GET_DESCUENTO_SUCCESS",
	GET_DESCUENTO_FAILED:"GET_DESCUENTO_FAILED",

	GET_FACTURAS_START:"GET_FACTURAS_START",
	GET_FACTURAS_SUCCESS:"GET_FACTURAS_SUCCESS",
	GET_FACTURAS_FAILED:"GET_FACTURAS_FAILED",


	UPDATE_PROFILE_START:"UPDATE_PROFILE_START",
	UPDATE_PROFILE_SUCCESS:"UPDATE_PROFILE_SUCCESS",
	UPDATE_PROFILE_FAILED:"UPDATE_PROFILE_FAILED",

	UPDATE_REGISTER_PROFILE:"UPDATE_REGISTER_PROFILE"
};
