export const emailCompanies = [
    'FEDEX',
    'UPS',
    'DHL',
    'USPS',
    'AMZL US',
    'LASERSHIP',
    'SWISSPOST',
    'TNT',
    'ARAMEX',
    'PARCELFORCE',
    'CHINA POST',
    'EMS',
    'INDIA POST',
    'JAPAN POST',
    'ROYAL MALL',
    'A1 INT',
    'CEVA',
    'CITY LINK',
    'DPD',
    'MAIL EXPRESS',
    'ONTRAC',
    'OSM WORLDWIDE',
    'PRESTIGE',
    'PUROLATOR',
    'STREAMLITE',
    'YRC',
    'OTROS...',

]