const Screens = {
   NewUser:"NewUser",
   Pass:"Pass",
   SignupData:"SignupData",
   SignupDelivery:"SignupDelivery",
   SignupFinal:"SignupFinal",
   Exito:"Exito",
   History:"History",
   Notifications:"Notifications",
   Profile:'Profile',
   ChangePassword:'ChangePassword',
   ChangeEmail:'ChangeEmail',
   DeleteAccount:'DeleteAccount',
   Help:"Help",
   Sessions:"Sessions",
   Contact:"Contact",
   ContactUs:"ContactUs",
   Funcionamiento:"Funcionamiento",
   Politicas:"Politicas",
   Consultas:"Consultas",
   Tarifas:"Tarifas",
   Funcionamiento1:"Funcionamiento1",
   Pago:"Pago",
   Envios:"Envios",
   Direcciones:"Direcciones",
   Facturas:"Facturas",
   Obtenerlos: "Obtenerlos",
   Canjear: "Canjear",
   Billetera: "Billetera",
   Reservas: "Reservas",
   GenerarReserva:"GenerarReserva",
   ComoLlegar: "ComoLlegar",
   ExitoReserva: "ExitoReserva",
   Home: "Home",
   RealizarPago: "RealizarPago",
   CreateActivity: "CreateActivity",
   DeleteActivity: "DeleteActivity",
   ModifyActivity: "ModifyActivity",
};

export default Screens;
