export const ActionTypes = {
    //--------------Login Action Types------------
	LOGIN_USER: "LOGIN_USER",	
	AUTO_LOGIN_SUCCESS:"AUTO_LOGIN_SUCCESS",
	LOG_OUT:"LOG_OUT",
	CHANGE_NAVIGATION_KEY:"CHANGE_NAVIGATION_KEY",
	GET_PRODUCTS:'GET_PRODUCTS',
	UPDATE_PROFILE:'UPDATE_PROFILE',
	UPDATE_SIGNUP_PROFILE:'UPDATE_SIGNUP_PROFILE'
};
