require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Easyclub' do

  # Pods for Tododeusa
  pod 'Firebase/Messaging'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'


  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'EasyclubTests' do
    inherit! :complete
    # Pods for testing
  end

end
