require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Tododeusa' do

  # Pods for Tododeusa
  pod 'Firebase/Messaging'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'TododeusaTests' do
    inherit! :complete
    # Pods for testing
  end

end

target 'Tododeusa-tvOS' do
  # Pods for Tododeusa-tvOS

  target 'Tododeusa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

